# Generated by Django 3.1.2 on 2020-12-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201222_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenter',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
