# Generated by Django 3.1.2 on 2021-01-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201222_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='profile',
            field=models.TextField(blank=True, help_text='Enter blogger biography', null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='commenter',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(help_text='Enter your blog post here'),
        ),
        migrations.DeleteModel(
            name='CommentCreate',
        ),
    ]
